# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iHobby_Portfolio4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iHobby_Portfolio4

pod 'GoogleMaps'
pod 'GooglePlaces'

pod 'FacebookCore'
pod 'FacebookLogin'

 pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'


end
